#!/usr/bin/php

<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';

class SmugClient{
    const TOKEN = "gnXh7ZH5X77tSVkqgKXXfpkj9xpmXm6T";
    CONST TOKEN_SEC = "BWPJTxNQDt9DdKJ9FWzGx4Bk3NZc9GjMQBVBMz247j8d88xpJG2QkPQ5VDk835JT";
    const APP_NAME = 'myApp';
    const VERBOSITY = 1;
    const OAUTH_SEC = 'bpvQdjcxgtrQQGGzjv6hCn8qJR6vCRV56rHH37Dm4dvkX9cqzLZqGhfPw2bH9f7B';
    const ACCESS = 'Full';
    const PERMISSION = 'Modify';
    const API_KEY = 'N98SRGkT8sgWBnstKwCPX7nj2Rwhd6K6';

    private $client = null;
    private $uploadFolderInfo = null;
    private $fileInfo = [];

    private function setToken(){
        $authtoken = array(
            "oauth_token" => self::TOKEN,
            "oauth_token_secret" => self::TOKEN_SEC
        );
        $this->client->setToken($authtoken['oauth_token'], $authtoken['oauth_token_secret']);
    }

    public function connect(){
        $options = [ 'AppName' => self::APP_NAME, 
            '_verbosity' => self::VERBOSITY, 
            'OAuthSecret' => self::OAUTH_SEC
        ];
        $this->client = new phpSmug\Client(self::API_KEY, $options);
        $this->setToken();
    }

    public function getClient(){
        return $this->client;
    }
}

function parameterIndexedArray($array){
    $indexedArray = [];
    $array = explode(",", $array);
    foreach($array as $value){
        $keyvalue = explode("=", $value);
        if(count($keyvalue)!= 2) continue;
        $indexedArray[$keyvalue[0]] = $keyvalue[1];
    }
    return $indexedArray;
}

function getPathResponse($str, $array){
    $result = $array;
    $path = explode(",", $str);
    foreach($path as $v){
        if(trim($v) == "") continue;
        if(is_array($result)){
            $result = $result[$v];    
        }
        else $result = $result->$v;
    }
    return $result;
}

$opt = getopt("o:p:c:");
$options = [];
$path = "";
$command = "get";
$uri = $argv[$argc-1];

if(array_key_exists('o', $opt)){
    $options=parameterIndexedArray($opt['o']);
}
if(array_key_exists('p', $opt)){
    $path=$opt['p'];
}
if(array_key_exists('c', $opt)){
    $command=$opt['c'];
}

$smugClient = new SmugClient();
$smugClient->connect();
$client = $smugClient->getClient();

echo "\n";
try{
    if($command == "get")
    print_r(getPathResponse($path, $client->get($uri, $options)));
else if($command == "post")
    print_r(getPathResponse($path, $client->post($uri, $options)));
else if($command == "options")
    print_r(getPathResponse($path, $client->options($uri, $options)));
}catch(GuzzleHttp\Exception\ClientException $e){
    print_r(
        getPathResponse($path, json_decode($e->getResponse()->getBody()->getContents())));
}

echo "\n";
echo "\n";
