<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';

class SmugClient{
    const TOKEN = "gnXh7ZH5X77tSVkqgKXXfpkj9xpmXm6T";
    CONST TOKEN_SEC = "BWPJTxNQDt9DdKJ9FWzGx4Bk3NZc9GjMQBVBMz247j8d88xpJG2QkPQ5VDk835JT";
    const APP_NAME = 'myApp';
    const VERBOSITY = 1;
    const OAUTH_SEC = 'bpvQdjcxgtrQQGGzjv6hCn8qJR6vCRV56rHH37Dm4dvkX9cqzLZqGhfPw2bH9f7B';
    const ACCESS = 'Full';
    const PERMISSION = 'Modify';
    const API_KEY = 'N98SRGkT8sgWBnstKwCPX7nj2Rwhd6K6';

    private $client = null;
    private $uploadFolderInfo = null;
    private $fileInfo = [];

    private function setToken(){
        $authtoken = array(
            "oauth_token" => self::TOKEN,
            "oauth_token_secret" => self::TOKEN_SEC
        );
        $this->client->setToken($authtoken['oauth_token'], $authtoken['oauth_token_secret']);
    }

    public function connect(){
        $options = [ 'AppName' => self::APP_NAME, 
            '_verbosity' => self::VERBOSITY, 
            'OAuthSecret' => self::OAUTH_SEC
        ];
        $this->client = new phpSmug\Client(self::API_KEY, $options);
        $this->setToken();
    }

    public function getClient(){
        return $this->client;
    }
}

function parameterIndexedArray($array){
    $indexedArray = [];
    $array = explode(",", $array);
    foreach($array as $value){
        $keyvalue = explode("=", $value);
        if(count($keyvalue)!= 2) continue;
        $indexedArray[$keyvalue[0]] = $indexedArray[1];
    }
    return $indexedArray;
}

function getPathResponse($str, $array){
    $result = $array;
    $path = explode(",", $str);
    foreach($path as $v){
        if($v == "") continue;
        if(is_array($result)){
            $result = $result[$v];    
        }
        else $result = $result->$v;
    }
    return $result;
}

$uri=$argv[1];
if($argc > 2) $path=$argv[2];
else $path = "";
if($argc > 3) $options=parameterIndexedArray($argv[3]);
else $options = [];

$smugClient = new SmugClient();
$smugClient->connect();
$client = $smugClient->getClient();

echo "\n";
print_r(getPathResponse($path, $client->get($uri, $options)));
echo "\n";
echo "\n";
