<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';




// Optional, but definitely nice to have, options
$options = [
        'AppName' => "myApp",
        '_verbosity' => 1, # Reduce verbosity to reduce the amount of data in the response and to make using it easier.
        'OAuthSecret' => "bpvQdjcxgtrQQGGzjv6hCn8qJR6vCRV56rHH37Dm4dvkX9cqzLZqGhfPw2bH9f7B", # You need to pass your OAuthSecret in order to authenticate with OAuth.
];

$perms = [
    'Access' => 'Full',
    'Permissions' => 'Modify',
];

$client = new phpSmug\Client('N98SRGkT8sgWBnstKwCPX7nj2Rwhd6K6', $options);

//$token = $client->getRequestToken("oob");
//print_r($token);
//echo $client->getAuthorizeURL($perms);

echo "\n";

//$client = new phpSmug\Client('N98SRGkT8sgWBnstKwCPX7nj2Rwhd6K6', $options);
/*$token = array(
    "oauth_token" => 'Zfq3cnQQfTpcVjmQv8pFzPgz97X8sbgj',
    "oauth_token_secret" => 'NkfWSXCs4s3r7W5VdSBGQtdc7k83z4zjGRCScv5gZBDk3kgtSBT6tP6gFgfCbRDM',
    "oauth_callback_confirmed" => true
);


$client->setToken($token['oauth_token'], $token['oauth_token_secret']);
$atoken = $client->getAccessToken('500634');
print_r($atoken);*/

$authtoken = array(
    "oauth_token" => "gnXh7ZH5X77tSVkqgKXXfpkj9xpmXm6T",
    "oauth_token_secret" => "BWPJTxNQDt9DdKJ9FWzGx4Bk3NZc9GjMQBVBMz247j8d88xpJG2QkPQ5VDk835JT"
);

$client->setToken($authtoken['oauth_token'], $authtoken['oauth_token_secret']);

$album = $client->get(
    'folder/user/rapha/Uploads!albumlist'
);


function createAlbumIfNotExists($client, $name){
    echo "folder/user/rapha/$name!albumlist";
    //try{
        $folder = $client->get(
            "album!search",
            array(
                'Scope' => 'folder/user/rapha/Uploads',
                'Text' => $name
                )
        );
        $count = $folder->Pages->Total;
        if($count > 0){
            echo "\tAlbum ja existe\n";
        }
        else echo "\tcriando album\n";
}

createAlbumIfNotExists($client, 'Teste');
createAlbumIfNotExists($client, 'Teste2');
//$folder = createFolderIfNotExists($client, 'Uploads2');


//  $albums = $client->get('user/rapha!albums');
//  foreach($albums->Album as $album){
//      $name = $album->Name;
//      echo "\n albumName: $name\n";
//      print_r($album->Uris->AlbumImages);
//      if($name == "AllPhotos2"){
//          $images = $client->get($album->Uris->AlbumImages, array('count' => 25));
//          print_r($images->AlbumImage[0]);
//          echo "title ; " + $images->AlbumImage[0]->Title;
//      };
//  }

/*
 processFolder(folder)
    if(folder_contains_images)
        get tagname from folderName
        get_file_with_img_info
        each image
            if image in file
                if checksum not match
                    delete photimg_tag = tagnameo from smugmug
                    upload new version
                    img_tag = tagname
            else 
                upload new version
                img_tag = tagname
        end
    each subfolder
        processFolder(subolder)
        */


function doUpload($dir){
    $folders = getFolders($dir);
    for($folder in $folders){
        $album = createAlbumIfNotExists($folder);
        $localImages = getLocalImageNames($folder);
        $remoteImages = getRemoteImageNames($album);
        for($localImg in $localImages){
            if($localImg->checksum != $remoteImages[$localImg->name]->checksum){
                $result = uploadImage($album, $localImg->name);
                logResult($album, $img, $result);
            }
        }
        
    }
}