<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';

function info($txt){
    echo "  $txt\n";
}

function error(){}

class Logger{
    const LOG = "main.log";
    const UPLOAD_ERRORS = "upload-errors.log";
    const PROCESSED = "processed.log";
    const SKIP = "skip.log";
    const TIME_FORMAT = "Y-m-d:H:i:s";

    private static function getTime(){
        $date = new DateTime(null, new DateTimeZone('America/Sao_Paulo'));
        return $date->format(self::TIME_FORMAT);
    }

    private static function writeLog($txt){
        file_put_contents(self::LOG, self::getTime() . " $txt", FILE_APPEND);
    }

    public static function info($txt){
        self::writeLog("INFO: " . "$txt\n");
    }

    public static function error($txt){
        self::writeLog("ERROR: " . "$txt\n");
    }

    public static function infoProcessed($file){
        self::info("Processing file $file...\n");
        file_put_contents(self::PROCESSED, "$file\n", FILE_APPEND);
    }

    public static function infoSkip($file){
        self::info("Arquivo $file não alterado, não será enviado.\n");
        file_put_contents(self::SKIP, "$file\n", FILE_APPEND);
    }

    public static function errorUpload($file){
        self::info("Um erro ocorreu durante o upload do arquivo $file, arquivo não será enviado!\n");
        file_put_contents(self::UPLOAD_ERRORS, "$file\n", FILE_APPEND);
    }
}

class SmugClient{
    const TOKEN = "gnXh7ZH5X77tSVkqgKXXfpkj9xpmXm6T";
    CONST TOKEN_SEC = "BWPJTxNQDt9DdKJ9FWzGx4Bk3NZc9GjMQBVBMz247j8d88xpJG2QkPQ5VDk835JT";
    const APP_NAME = 'myApp';
    const VERBOSITY = 1;
    const OAUTH_SEC = 'bpvQdjcxgtrQQGGzjv6hCn8qJR6vCRV56rHH37Dm4dvkX9cqzLZqGhfPw2bH9f7B';
    const ACCESS = 'Full';
    const PERMISSION = 'Modify';
    const API_KEY = 'N98SRGkT8sgWBnstKwCPX7nj2Rwhd6K6';

    private $client = null;
    private $uploadFolderInfo = null;
    private $fileInfo = [];

    private function setToken(){
        $authtoken = array(
            "oauth_token" => self::TOKEN,
            "oauth_token_secret" => self::TOKEN_SEC
        );
        $this->client->setToken($authtoken['oauth_token'], $authtoken['oauth_token_secret']);
    }

    public function connect(){
        Logger::info("Connecting to smugmug...");
        if($this->client != null){
            Logger:info("Already connected!");
            return $this->client;
        }
        $options = [ 'AppName' => self::APP_NAME, 
            '_verbosity' => self::VERBOSITY, 
            'OAuthSecret' => self::OAUTH_SEC
        ];
        $this->client = new phpSmug\Client(self::API_KEY, $options);
        $this->setToken();
        $this->getFolderUploads(true);
        Logger::info("OK!");
        return $this->client;
    }

    private function getFolderUploads($force){
        if($this->uploadFolderInfo == null || $force){
            $this->uploadFolderInfo = $this->client->get("folder/user/rapha/Uploads!albums");
        }
        return $this->uploadFolderInfo;
    }

    private function getAlbumInfo($name){
        $uploadsInfo = $this->getFolderUploads(false);
        if(!isset($uploadsInfo->Album) || count($uploadsInfo->Album) == 0){
            return false;
        } 
            
        $albums = $uploadsInfo->Album;
        foreach($albums as $album){
            if($album->Name == ucfirst($name)) return $album;
        }
        return null;
    }

    private function getImageInfo($album) {
        if(!array_key_exists($album, $this->fileInfo) || 
            $this->fileInfo[$album] == null){
            $albumKey = $this->getAlbumInfo($album)->AlbumKey;
            $this->fileInfo[$album] = $this->client->get("album/$albumKey!images");
        }
        return $this->fileInfo[$album];
    }

    public function getMd5Sums($album, $imageName){
        $imageInfo = $this->getImageInfo($album);
        if(!array_key_exists("AlbumImage", $imageInfo)) return null;
        foreach($imageInfo->AlbumImage as $info){
            if($info->FileName == $imageName) return $info->ArchivedMD5;
        }
        return null;
    }

    public function albumExists($name){
        try{
            return $this->getAlbumInfo($name) != null;
        }catch(Exception $e){
            if($e->getResponse()->getStatusCode() == 404){
                return false;
            }
        }
    }

    public function createAlbum($name, $tags){
        $urlCreate = 'folder/user/rapha/Uploads!albums';
        $albumOptions = [
            "Name" => ucfirst($name),
            "Keywords" => $tags,
            "Privacy" => 3,
            "UrlName" => ucfirst($name),
            "Watermark" => false,
        ];
        try{
            $this->client->post($urlCreate, $albumOptions);
            $uploads = $this->getFolderUploads(true);
        }catch(Exception $e){
            print($e->getResponse()->getBody(true));
        }
    }

    public function upload($file, $album, $tags){
        $albumKey = $this->getAlbumInfo($album)->AlbumKey;
        $this->client->upload("album/$albumKey", $file, [
            'FileName' => $file,
            'Keywords' => $tags
        ]);
    }
}

class Uploader {
    const MEDIA_PATTERN = "{jpg,JPG,png,PNG}";

    private $client = null;
    private $smugClient;

    function connect() {
        $this->smugClient = new SmugClient();
        try{
            $this->client = $this->smugClient->connect();
        }catch(Exception $e){
            Logger::error("Conection error " . $e->getMessage());
            throw($e);
        }
   }

    private function log($text){
        echo "  $text\n";
    }

    private function getFolderName($path){
        return basename($path);
    }

    private function getTags($path){
        $tags = explode('/', $path);
        $filter = function($value) {
            if($value == '.' || $value == "") return false;
            return true;
        };
        $tags = array_filter($tags, $filter);
        $tags = array_slice($tags, 1);
        return implode(",", $tags);
    }

    private function createAlbumIfNotExists($path, $tags){
        $albumName = $this->getFolderName($path);
        Logger::info("Searching for $albumName album...");
        if($this->smugClient->albumExists($albumName)){
            Logger::info("\tAlbum found");
        }
        else{
            Logger::info("\tAlbum not found, creating it...");
            $this->smugClient->createAlbum($albumName, $tags);
        }
    }

    private function getDirs($parent){
        Logger::info("Getting subdirectories from $parent...");
        $dirs = glob($parent . '/*' , GLOB_ONLYDIR);
        return $dirs;
    }
    
    private function getPhotos($dir){
        Logger::info("Searching for media in $dir directory ...");
        return glob("$dir/*.". self::MEDIA_PATTERN, GLOB_BRACE);
    }


    private function sendFiles($path){
        $albumName = $this->getFolderName($path);
        $files = $this->getPhotos($path);
        $tags = $this->getTags($path);
        if(count($files)== 0){
            Logger::info("Directory $path has no media files, nothing to do here!");
            return;
        }

        $this->createAlbumIfNotExists($path, $tags);
        foreach($files as $file){
            Logger::infoProcessed($file);
            $md5 = $this->smugClient->getMd5Sums($albumName, $this->getFolderName($file));
            if($md5 != null && md5_file($file) == $md5){
                Logger::infoSkip($file);
                continue;
            }
            
            Logger::info("Uploading $file...");
            try{
                $this->smugClient->upload($file, $albumName, $tags);
            }catch(Exception $e){
                Logger::error("Error during file upload($file), file will be skiped.");
            }
        }
    }

    public function processDir($path) {
        Logger::info("Processing directory $path...");
        $dirs = $this->getDirs($path);
        if(count($dirs) > 0){
            Logger::info("Directory $path contains children, processing them first...");
        }
        foreach($dirs as $child){
            $this->processDir($child);
        }
        $this->sendFiles($path);
    }
   
}

$uploader = new Uploader();
try{
    Logger::info("Start scripting in " . $argv[1] . "...");
    $uploader->connect();
    $uploader->processDir($argv[1]);
    Logger::info("End processing.");
}catch(Exception $e){
    echo "Um erro ocorreu finalizando. Cheque o arquivo main.log.\n";
}
